FROM node:22-alpine AS base
WORKDIR /app
RUN corepack enable
COPY . .
RUN pnpm install --frozen-lockfile=false
RUN pnpm --filter @first-aid/api prisma:generate
RUN pnpm --filter @first-aid/worker build
CMD ["pnpm", "--filter", "@first-aid/worker", "start"]
